name: Latest Youtube Videos 
on: 
  schedule:
    # Rruns very hour 
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: update this repo's README with lates videos from Youtube
    runs-on: ubuntu-lates
    steps: 
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with: 
          comment_tag_name: "Youtube"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCCNG9rI9Uz9dOpxBLM8ELNA"